// src/data.ts

export interface Pedra {
  id: number;
  nome: string;
  tipo: 'Caco' | 'Quartzito'| 'Granito' | 'Pedra Diversa';
  descricao: string;
  imagem: string;
  usoRecomendado: string;
  cuidados: string;
  caracteristicas: string;
  peso: string;
  dimensoes: string;
}

export const pedras: Pedra[] = [
  // Pedras Diversas
  {
    id: 1,
    nome: 'Cacão Pisada de Jardim',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra natural ideal para revestir jardins, proporcionando um visual elegante e resistente.',
    imagem: '/images/pedras/cacao-pisada-jardim.jpg',
    usoRecomendado: 'Jardins, áreas de lazer externas, caminhos e pátios.',
    cuidados: 'Limpar regularmente com água e sabão neutro. Evitar produtos químicos abrasivos.',
    caracteristicas: 'Durável, antideslizante, resistente a intempéries.',
    peso: '25 kg/m²',
    dimensoes: '30x30 cm',
  },
  {
    id: 2,
    nome: 'Caco de Pedra Ferro',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra resistente com aparência rústica, perfeita para projetos que exigem durabilidade e estilo.',
    imagem: '/images/pedras/caco-pedra-ferro.jpg',
    usoRecomendado: 'Revestimentos de paredes externas, lajes e calçadas.',
    cuidados: 'Manutenção periódica com aplicação de selante. Limpeza com água e escova macia.',
    caracteristicas: 'Rústica, alta resistência, fácil manutenção.',
    peso: '30 kg/m²',
    dimensoes: '40x20 cm',
  },
  {
    id: 3,
    nome: 'Caco de Pedra São Tomé',
    tipo: 'Pedra Diversa',
    descricao: 'Caco de Pedra São Tomé, altamente durável e com excelente acabamento para diversas aplicações.',
    imagem: '/images/pedras/caco-pedra-sao-tome.jpg',
    usoRecomendado: 'Pisos internos e externos, áreas comerciais e residenciais.',
    cuidados: 'Limpar com produtos neutros. Evitar exposição prolongada a agentes químicos.',
    caracteristicas: 'Durável, versátil, acabamento suave.',
    peso: '28 kg/m²',
    dimensoes: '35x25 cm',
  },
  {
    id: 4,
    nome: 'Pedra Mineira',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra natural ideal para revestimentos externos, combinando beleza e resistência.',
    imagem: '/images/pedras/pedra-mineira.jpg',
    usoRecomendado: 'Revestimentos de fachadas, jardins e pátios.',
    cuidados: 'Limpeza regular com água e sabão. Aplicar impermeabilizante anualmente.',
    caracteristicas: 'Beleza natural, resistente a intempéries, fácil manutenção.',
    peso: '32 kg/m²',
    dimensoes: '40x30 cm',
  },
  {
    id: 5,
    nome: 'Pedra Miracema',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Miracema utilizada para calçadas e pavimentações, oferecendo durabilidade e estética.',
    imagem: '/images/pedras/pedra-miracema.jpg',
    usoRecomendado: 'Calçadas, caminhos, pátios e áreas de lazer.',
    cuidados: 'Manter livre de detritos e limpezas periódicas com água. Evitar produtos abrasivos.',
    caracteristicas: 'Resistente, antideslizante, acabamento elegante.',
    peso: '27 kg/m²',
    dimensoes: '45x20 cm',
  },
  {
    id: 6,
    nome: 'Pedra Quartzito',
    tipo: 'Quartzito',
    descricao: 'Pedra quartzito de alta resistência e beleza, ideal para diversas aplicações arquitetônicas.',
    imagem: '/images/pedras/pedra-quartzito.jpg',
    usoRecomendado: 'Revestimentos internos e externos, bancadas e pisos.',
    cuidados: 'Limpeza com produtos adequados para pedra natural. Aplicar selante periodicamente.',
    caracteristicas: 'Alta resistência, variedade de cores, acabamento polido.',
    peso: '35 kg/m²',
    dimensoes: '50x25 cm',
  },
  {
    id: 7,
    nome: 'Pedra São Tomé',
    tipo: 'Quartzito',
    descricao: 'Pedra São Tomé, perfeita para pisos e paredes, oferecendo uma combinação única de beleza e durabilidade.',
    imagem: '/images/pedras/pedra-sao-tome.jpg',
    usoRecomendado: 'Pisos, paredes internas e externas, áreas comerciais.',
    cuidados: 'Manutenção com produtos específicos para pedra natural. Evitar exposição a produtos químicos agressivos.',
    caracteristicas: 'Elegante, resistente, versátil.',
    peso: '29 kg/m²',
    dimensoes: '40x40 cm',
  },
  {
    id: 8,
    nome: 'Piso de Ardósia',
    tipo: 'Pedra Diversa',
    descricao: 'Piso de ardósia com durabilidade e estilo rústico, ideal para ambientes que buscam um toque natural.',
    imagem: '/images/pedras/piso-ardosia.jpg',
    usoRecomendado: 'Pisos de áreas internas e externas, áreas comerciais e residenciais.',
    cuidados: 'Limpeza com vassoura e água. Evitar produtos químicos que possam manchar.',
    caracteristicas: 'Rústico, resistente, antideslizante.',
    peso: '33 kg/m²',
    dimensoes: '60x30 cm',
  },
  {
    id: 9,
    nome: 'Piso de Granito',
    tipo: 'Granito',
    descricao: 'Piso de granito com alta durabilidade, ideal para ambientes que exigem resistência e elegância.',
    imagem: '/images/pedras/piso-granito.jpg',
    usoRecomendado: 'Pisos de residências, comércios e áreas industriais.',
    cuidados: 'Limpeza regular com produtos neutros. Aplicar selante anualmente para manter o brilho.',
    caracteristicas: 'Durável, elegante, resistente a riscos e manchas.',
    peso: '38 kg/m²',
    dimensoes: '50x50 cm',
  },
  {
    id: 10,
    nome: 'Filetão Pedra Madeira',
    tipo: 'Pedra Diversa',
    descricao: 'Filetão de Pedra Madeira usado em revestimentos, proporcionando um visual sofisticado e natural.',
    imagem: '/images/pedras/filetao-pedra-madeira.jpg',
    usoRecomendado: 'Revestimentos de paredes internas, lareiras e detalhes arquitetônicos.',
    cuidados: 'Limpeza com pano úmido e sabão neutro. Evitar produtos abrasivos.',
    caracteristicas: 'Sofisticado, natural, fácil de limpar.',
    peso: '22 kg/m²',
    dimensoes: '30x10 cm',
  },
  {
    id: 11,
    nome: 'Filete de Pedra Canjiquinha',
    tipo: 'Pedra Diversa',
    descricao: 'Filete de Pedra Canjiquinha para decoração de paredes, oferecendo um acabamento elegante.',
    imagem: '/images/pedras/filete-canjiquinha.jpg',
    usoRecomendado: 'Revestimentos de paredes internas, detalhes decorativos.',
    cuidados: 'Limpeza com pano úmido. Evitar impacto direto com produtos químicos.',
    caracteristicas: 'Elegante, decorativo, fácil manutenção.',
    peso: '20 kg/m²',
    dimensoes: '25x10 cm',
  },
  {
    id: 12,
    nome: 'Pedra Ferro',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Ferro com alta resistência e estilo rústico, ideal para diversos tipos de revestimentos.',
    imagem: '/images/pedras/pedra-ferro.jpg',
    usoRecomendado: 'Revestimentos de fachadas, pisos externos e lajes.',
    cuidados: 'Manter limpa e aplicar selante periodicamente. Evitar produtos abrasivos.',
    caracteristicas: 'Rústica, resistente, fácil de manter.',
    peso: '30 kg/m²',
    dimensoes: '40x20 cm',
  },
  {
    id: 13,
    nome: 'Pedra Madeira',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Madeira ideal para revestimentos internos e externos, combinando beleza natural com durabilidade.',
    imagem: '/images/pedras/pedra-madeira.jpg',
    usoRecomendado: 'Revestimentos de paredes, pisos e áreas externas.',
    cuidados: 'Limpeza com pano úmido e sabão neutro. Aplicar impermeabilizante conforme necessário.',
    caracteristicas: 'Natural, durável, versátil.',
    peso: '28 kg/m²',
    dimensoes: '35x15 cm',
  },
  {
    id: 14,
    nome: 'Pedra Madeira Bruta',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Madeira em estado bruto, oferecendo uma aparência natural e rústica.',
    imagem: '/images/pedras/pedra-madeira-bruta.jpg',
    usoRecomendado: 'Decoração de interiores, paredes rústicas e áreas de lazer.',
    cuidados: 'Manter limpa e protegida contra umidade excessiva. Evitar produtos químicos.',
    caracteristicas: 'Bruta, natural, rústica.',
    peso: '26 kg/m²',
    dimensoes: '40x20 cm',
  },
  {
    id: 15,
    nome: 'Pedra Madeira Serrada',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Madeira serrada para acabamentos elegantes em projetos de decoração.',
    imagem: '/images/pedras/pedra-madeira-serrada.jpg',
    usoRecomendado: 'Revestimentos finos, detalhes decorativos e áreas de destaque.',
    cuidados: 'Limpeza regular com pano seco ou ligeiramente úmido. Evitar produtos abrasivos.',
    caracteristicas: 'Elegante, serrada, acabamento refinado.',
    peso: '24 kg/m²',
    dimensoes: '30x10 cm',
  },
  {
    id: 16,
    nome: 'Pedra Moledo',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Moledo usada em paisagismo e decoração rústica, proporcionando um visual natural.',
    imagem: '/images/pedras/pedra-moledo.jpg',
    usoRecomendado: 'Paisagismo, jardins, muros e áreas de lazer externas.',
    cuidados: 'Manter livre de detritos e limpezas periódicas com água. Aplicar selante conforme necessário.',
    caracteristicas: 'Natural, rústica, resistente.',
    peso: '27 kg/m²',
    dimensoes: '35x20 cm',
  },
  {
    id: 17,
    nome: 'Tijolinhos Bricks',
    tipo: 'Pedra Diversa',
    descricao: 'Tijolinhos bricks para revestimentos rústicos, ideais para criar ambientes aconchegantes.',
    imagem: '/images/pedras/tijolinhos-bricks.jpg',
    usoRecomendado: 'Revestimentos de paredes internas e externas, detalhes arquitetônicos.',
    cuidados: 'Limpeza com vassoura e água. Evitar produtos químicos agressivos.',
    caracteristicas: 'Rústico, versátil, fácil de instalar.',
    peso: '23 kg/m²',
    dimensoes: '25x15 cm',
  },
  {
    id: 18,
    nome: 'Pedra Goias',
    tipo: 'Quartzito',
    descricao: 'Pedras serradas para acabamento de alta precisão, ideais para projetos detalhados.',
    imagem: '/images/pedras/pedras-serradas.jpg',
    usoRecomendado: 'Detalhes arquitetônicos, revestimentos finos e áreas de destaque.',
    cuidados: 'Limpeza com pano úmido e sabão neutro. Evitar impactos diretos.',
    caracteristicas: 'Preciso, elegante, fácil de manter.',
    peso: '25 kg/m²',
    dimensoes: '30x10 cm',
  },
  {
    id: 19,
    nome: 'Lajão',
    tipo: 'Pedra Diversa',
    descricao: 'Lajão utilizado em revestimentos de áreas amplas, oferecendo um visual robusto e natural.',
    imagem: '/images/pedras/lajao.jpg',
    usoRecomendado: 'Revestimentos de grandes áreas internas e externas, como lajes e pátios.',
    cuidados: 'Limpeza regular com água e sabão. Aplicar selante para proteger contra manchas.',
    caracteristicas: 'Robusto, natural, durável.',
    peso: '40 kg/m²',
    dimensoes: '60x30 cm',
  },
  {
    id: 20,
    nome: 'Retalhos',
    tipo: 'Pedra Diversa',
    descricao: 'Retalhos de pedras para projetos de mosaicos, oferecendo versatilidade e criatividade.',
    imagem: '/images/pedras/retalhos.jpg',
    usoRecomendado: 'Mosaicos decorativos, detalhes artísticos e projetos personalizados.',
    cuidados: 'Limpeza com produtos suaves. Evitar exposição a produtos químicos agressivos.',
    caracteristicas: 'Versátil, criativo, fácil de adaptar.',
    peso: '18 kg/m²',
    dimensoes: 'Diversas',
  },
  {
    id: 21,
    nome: 'Laje',
    tipo: 'Pedra Diversa',
    descricao: 'Laje de pedra natural para revestimentos externos, proporcionando um acabamento elegante e resistente.',
    imagem: '/images/pedras/laje.jpg',
    usoRecomendado: 'Revestimentos de fachadas, pisos externos e áreas de lazer.',
    cuidados: 'Manter limpa e aplicar impermeabilizante conforme necessário. Evitar produtos abrasivos.',
    caracteristicas: 'Elegante, resistente, durável.',
    peso: '35 kg/m²',
    dimensoes: '50x30 cm',
  },
  {
    id: 22,
    nome: 'Pedra Caverna',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Caverna com acabamento rústico e natural, ideal para projetos que buscam um visual único.',
    imagem: '/images/pedras/pedra-caverna.jpg',
    usoRecomendado: 'Revestimentos de paredes internas, áreas de estar e decoração rústica.',
    cuidados: 'Limpeza com pano úmido e sabão neutro. Evitar impactos diretos.',
    caracteristicas: 'Rústica, natural, única.',
    peso: '29 kg/m²',
    dimensoes: '40x20 cm',
  },
  {
    id: 23,
    nome: 'Pedra Atacama',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Atacama com tonalidades naturais, perfeita para revestimentos que valorizam a estética natural.',
    imagem: '/images/pedras/pedra-atacama.jpg',
    usoRecomendado: 'Revestimentos de pisos, paredes e áreas externas.',
    cuidados: 'Manter limpa com água e sabão neutro. Aplicar selante para proteção adicional.',
    caracteristicas: 'Natural, tonalidades variadas, resistente.',
    peso: '31 kg/m²',
    dimensoes: '45x25 cm',
  },
  {
    id: 24,
    nome: 'Seixos',
    tipo: 'Pedra Diversa',
    descricao: 'Seixos naturais para decoração de jardins e interiores, adicionando um toque natural e elegante.',
    imagem: '/images/pedras/seixos.jpg',
    usoRecomendado: 'Decoração de jardins, aquários, caminhos e detalhes decorativos.',
    cuidados: 'Manter limpos e livres de detritos. Reabastecer conforme necessário.',
    caracteristicas: 'Natural, elegante, fácil de combinar.',
    peso: '15 kg/m²',
    dimensoes: 'Diversas',
  },
  {
    id: 25,
    nome: 'Moledo',
    tipo: 'Pedra Diversa',
    descricao: 'Moledo usado em decoração paisagística, proporcionando um visual natural e resistente.',
    imagem: '/images/pedras/pedra-moledo.jpg',
    usoRecomendado: 'Paisagismo, jardins, muros e áreas de lazer externas.',
    cuidados: 'Limpeza regular com água. Aplicar selante para manter a aparência.',
    caracteristicas: 'Natural, resistente, versátil.',
    peso: '28 kg/m²',
    dimensoes: '35x25 cm',
  },
  {
    id: 26,
    nome: 'Pedra Vila Velha',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Vila Velha com tons terrosos, ideal para projetos que buscam um visual acolhedor e natural.',
    imagem: '/images/pedras/pedra-vila-velha.jpg',
    usoRecomendado: 'Revestimentos de paredes, pisos e áreas externas.',
    cuidados: 'Manter limpa com água e sabão neutro. Evitar produtos químicos abrasivos.',
    caracteristicas: 'Acolhedora, natural, durável.',
    peso: '30 kg/m²',
    dimensoes: '40x30 cm',
  },
  {
    id: 27,
    nome: 'Filetes',
    tipo: 'Pedra Diversa',
    descricao: 'Filetes de pedra usados para revestimentos decorativos, oferecendo um acabamento refinado.',
    imagem: '/images/pedras/filetes.jpg',
    usoRecomendado: 'Detalhes arquitetônicos, revestimentos finos e áreas de destaque.',
    cuidados: 'Limpeza com pano úmido. Evitar produtos abrasivos e impactos diretos.',
    caracteristicas: 'Refinado, decorativo, fácil de limpar.',
    peso: '22 kg/m²',
    dimensoes: '30x10 cm',
  },
  {
    id: 28,
    nome: 'Pé de Moleque / Arrimo',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Pé de Moleque ideal para arrimo e sustentação, oferecendo robustez e durabilidade.',
    imagem: '/images/pedras/pe-de-moleque.jpg',
    usoRecomendado: 'Arrimos, sustentação de paredes, projetos de engenharia civil.',
    cuidados: 'Manter livre de detritos. Inspecionar regularmente para garantir a integridade.',
    caracteristicas: 'Robusta, durável, resistente.',
    peso: '40 kg/m²',
    dimensoes: '50x50 cm',
  },
  {
    id: 29,
    nome: 'Pedra Portuguesa',
    tipo: 'Pedra Diversa',
    descricao: 'Pedra Portuguesa usada em pavimentação e mosaicos, oferecendo versatilidade e beleza.',
    imagem: '/images/pedras/pedra-portuguesa.jpg',
    usoRecomendado: 'Pavimentação de áreas externas, mosaicos decorativos e revestimentos.',
    cuidados: 'Limpeza com água e sabão neutro. Aplicar selante para proteção contra manchas.',
    caracteristicas: 'Versátil, bonita, durável.',
    peso: '35 kg/m²',
    dimensoes: '40x20 cm',
  },
  
];
